### ISSUE TITLE
请问有RTOS3.0的版本吗？

### ISSUE THREAD

**Issue by sonwa** [HoGC/ESP8266_MQTT_DC1#1]
请问有RTOS3.0的版本吗？

**Comment by HoGC** [comment]
我没有写，但是你自己移植下DC1的驱动就行，或者直接用NONOS开发。

**Comment by sonwa** [comment]
用RTOS的i2c事例弄了下按键事件的，但加多几个if判断就会初始化挂了在i2c_master_cmd_begin上。

**Comment by HoGC** [comment]
有空我尝试下

**Comment by sonwa** [comment]
`/* I2C example
 
 This example code is in the Public Domain (or CC0 licensed, at your option.)
 
 Unless required by applicable law or agreed to in writing, this
 software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 CONDITIONS OF ANY KIND, either express or implied.
 */


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "esp_log.h"
#include "esp_system.h"
#include "esp_err.h"

#include "driver/i2c.h"
#include "driver/uart.h"

static const char *TAG = "main";

/**
 * TEST CODE BRIEF
 *
 * This example will show you how to use I2C module by running two tasks on i2c bus:
 *
 * - read external i2c sensor, here we use a MPU6050 sensor for instance.
 * - Use one I2C port(master mode) to read or write the other I2C port(slave mode) on one ESP8266 chip.
 *
 * Pin assignment:
 *
 * - master:
 *    GPIO14 is assigned as the data signal of i2c master port
 *    GPIO2 is assigned as the clock signal of i2c master port
 *
 * Connection:
 *
 * - connect sda/scl of sensor with GPIO14/GPIO2
 * - no need to add external pull-up resistors, driver will enable internal pull-up resistors.
 *
 * Test items:
 *
 * - read the sensor data, if connected.
 */

#define BUF_SIZE (128)

#define I2C_EXAMPLE_MASTER_SCL_IO           12                /*!< gpio number for I2C master clock */
#define I2C_EXAMPLE_MASTER_SDA_IO           3               /*!< gpio number for I2C master data  */
#define I2C_EXAMPLE_MASTER_NUM              I2C_NUM_0        /*!< I2C port number for master dev */
#define I2C_EXAMPLE_MASTER_TX_BUF_DISABLE   0                /*!< I2C master do not need buffer */
#define I2C_EXAMPLE_MASTER_RX_BUF_DISABLE   0                /*!< I2C master do not need buffer */

#define MPU6050_SENSOR_ADDR                 0x20             /*!< slave address for MPU6050 sensor */

uint8_t m_inp = 0x00;
uint8_t m_out = 0x00;
uint8_t pinNum2bitNum[] = { 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80 };
char pinNumStatus[] = {false, false, false, false, false, false, false, false};


#define MPU6050_CMD_START                   0x41             /*!< Command to set measure mode */
#define MPU6050_WHO_AM_I                    0x75             /*!< Command to read WHO_AM_I reg */
#define WRITE_BIT                           I2C_MASTER_WRITE /*!< I2C master write */
#define READ_BIT                            I2C_MASTER_READ  /*!< I2C master read */
#define ACK_CHECK_EN                        0x1              /*!< I2C master will check ack from slave*/
#define ACK_CHECK_DIS                       0x0              /*!< I2C master will not check ack from slave */
#define ACK_VAL                             0x0              /*!< I2C ack value */
#define NACK_VAL                            0x1              /*!< I2C nack value */
#define LAST_NACK_VAL                       0x2              /*!< I2C last_nack value */

/**
 * Define the mpu6050 register address:
 */
#define SMPLRT_DIV      0x19
#define CONFIG          0x1A
#define GYRO_CONFIG     0x1B
#define ACCEL_CONFIG    0x1C
#define ACCEL_XOUT_H    0x3B
#define ACCEL_XOUT_L    0x3C
#define ACCEL_YOUT_H    0x3D
#define ACCEL_YOUT_L    0x3E
#define ACCEL_ZOUT_H    0x3F
#define ACCEL_ZOUT_L    0x40
#define TEMP_OUT_H      0x41
#define TEMP_OUT_L      0x42
#define GYRO_XOUT_H     0x43
#define GYRO_XOUT_L     0x44
#define GYRO_YOUT_H     0x45
#define GYRO_YOUT_L     0x46
#define GYRO_ZOUT_H     0x47
#define GYRO_ZOUT_L     0x48
#define PWR_MGMT_1      0x6B
#define WHO_AM_I        0x75  /*!< Command to read WHO_AM_I reg */


//bool plugin4Status = false;
//bool plugin5Status = false;
//bool plugin6Status = false;
//bool plugin7Status = false;

/**
 * @brief i2c master initialization
 */
static esp_err_t i2c_example_master_init()
{
    int i2c_master_port = I2C_EXAMPLE_MASTER_NUM;
    i2c_config_t conf;
    conf.mode = I2C_MODE_MASTER;
    conf.sda_io_num = I2C_EXAMPLE_MASTER_SDA_IO;
    conf.sda_pullup_en = 0;
    conf.scl_io_num = I2C_EXAMPLE_MASTER_SCL_IO;
    conf.scl_pullup_en = 0;
    ESP_ERROR_CHECK(i2c_driver_install(I2C_EXAMPLE_MASTER_NUM, conf.mode));
    ESP_ERROR_CHECK(i2c_param_config(I2C_EXAMPLE_MASTER_NUM, &conf));
    return ESP_OK;
}

/**
 * @brief test code to write mpu6050
 *
 * 1. send data
 * ___________________________________________________________________________________________________
 * | start | slave_addr + wr_bit + ack | write reg_address + ack | write data_len byte + ack  | stop |
 * --------|---------------------------|-------------------------|----------------------------|------|
 *
 * @param i2c_num I2C port number
 * @param reg_address slave reg address
 * @param data data to send
 * @param data_len data length
 *
 * @return
 *     - ESP_OK Success
 *     - ESP_ERR_INVALID_ARG Parameter error
 *     - ESP_FAIL Sending command error, slave doesn't ACK the transfer.
 *     - ESP_ERR_INVALID_STATE I2C driver not installed or not in master mode.
 *     - ESP_ERR_TIMEOUT Operation timeout because the bus is busy.
 */
static esp_err_t i2c_example_master_mpu6050_write(i2c_port_t i2c_num, uint8_t reg_address, uint8_t *data, size_t data_len)
{
    int ret;
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, MPU6050_SENSOR_ADDR << 1 | WRITE_BIT, ACK_CHECK_EN);
    i2c_master_write_byte(cmd, reg_address, ACK_CHECK_EN);
    i2c_master_write(cmd, data, data_len, ACK_CHECK_EN);
    i2c_master_stop(cmd);
    ret = i2c_master_cmd_begin(i2c_num, cmd, 20 / portTICK_RATE_MS);
    i2c_cmd_link_delete(cmd);
    
    return ret;
}

/**
 * @brief test code to read mpu6050
 *
 * 1. send reg address
 * ______________________________________________________________________
 * | start | slave_addr + wr_bit + ack | write reg_address + ack | stop |
 * --------|---------------------------|-------------------------|------|
 *
 * 2. read data
 * ___________________________________________________________________________________
 * | start | slave_addr + wr_bit + ack | read data_len byte + ack(last nack)  | stop |
 * --------|---------------------------|--------------------------------------|------|
 *
 * @param i2c_num I2C port number
 * @param reg_address slave reg address
 * @param data data to read
 * @param data_len data length
 *
 * @return
 *     - ESP_OK Success
 *     - ESP_ERR_INVALID_ARG Parameter error
 *     - ESP_FAIL Sending command error, slave doesn't ACK the transfer.
 *     - ESP_ERR_INVALID_STATE I2C driver not installed or not in master mode.
 *     - ESP_ERR_TIMEOUT Operation timeout because the bus is busy.
 */
static esp_err_t i2c_example_master_mpu6050_read(i2c_port_t i2c_num, uint8_t reg_address, uint8_t *data, size_t data_len)
{
    int ret;
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, MPU6050_SENSOR_ADDR << 1 | WRITE_BIT, ACK_CHECK_EN);
    i2c_master_write_byte(cmd, reg_address, ACK_CHECK_EN);
    i2c_master_stop(cmd);
    ret = i2c_master_cmd_begin(i2c_num, cmd, 20 / portTICK_RATE_MS);
    i2c_cmd_link_delete(cmd);
    
    if (ret != ESP_OK) {
        return ret;
    }
    
    cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, MPU6050_SENSOR_ADDR << 1 | READ_BIT, ACK_CHECK_EN);
    i2c_master_read(cmd, data, data_len, LAST_NACK_VAL);
    i2c_master_stop(cmd);
    ret = i2c_master_cmd_begin(i2c_num, cmd, 20 / portTICK_RATE_MS);
    i2c_cmd_link_delete(cmd);
    
    return ret;
}

static esp_err_t i2c_example_master_mpu6050_init(i2c_port_t i2c_num)
{
    uint8_t cmd_data;
    //int ret;
    vTaskDelay(200 / portTICK_RATE_MS);
    i2c_example_master_init();
    cmd_data = 0x00;    // reset mpu6050
    ESP_ERROR_CHECK(i2c_example_master_mpu6050_write(i2c_num, 0x0, &cmd_data, 1));

    return ESP_OK;
}

bool digitalWrite(uint8_t pin, bool val) {
    if (pin >= sizeof(pinNum2bitNum)) {
        return false;
    }
    
    if (val) {
        //printf("~~~~HIGH\n");
        ////ESP_LOGI(TAG, "~~~~HIGH");
        m_out |= pinNum2bitNum[pin];
    } else {
        //printf("~~~~LOW\n");
        //ESP_LOGI(TAG, "~~~~LOW");
        m_out &= ~pinNum2bitNum[pin];
    }
    
    //ESP_LOGI(TAG, "m_out: 0x%02x\n", m_out);
    
    pinNumStatus[pin] = val;
    

    i2c_example_master_mpu6050_write(I2C_EXAMPLE_MASTER_NUM, 1, &m_out, 1);
    
    return true;
}


static void i2c_task_example(void *arg)
{
    //uint8_t sensor_data[14];
    //uint8_t who_am_i, i;
    //double Temp;
    //static uint32_t error_count = 0;
    //int ret;
    
    i2c_example_master_mpu6050_init(I2C_EXAMPLE_MASTER_NUM);
    //uint8_t cmd_data = 0;
    //uint8_t counts = 0;
    //int iNum = 0;
    //bool isOn = true;
    bool isPress = false;
    while (1) {
        
        uint8_t pin = 0x0f;
        i2c_example_master_mpu6050_read(I2C_EXAMPLE_MASTER_NUM, 0x00, &pin, 1);
        //ESP_LOGI(TAG, "pin: 0x%02x\n", pin);
        ESP_LOGI(TAG, "pin: 0x%02x03\n", pin);
        

        
        pin &= ~pinNum2bitNum[4];
        pin &= ~pinNum2bitNum[5];
        pin &= ~pinNum2bitNum[6];
        pin &= ~pinNum2bitNum[7];
        
        //if (isPress && pin_0 != 0x0f && pin_0 != 0x1f && pin_0 != 0x2f && pin_0 != 0x3f && pin_0 != 0x4f && pin_0 != 0x5f && pin_0 != 0x6f && pin_0 != 0x7f) {
        if (isPress && pin != 0x0f) {
            //ESP_LOGI(TAG, "~~~~~~~~continue");
            continue;
        } /*else {
            isPress = false;
        }*/

 
        
        ESP_LOGI(TAG, "%d,%d,%d,%d\n", pinNumStatus[4],pinNumStatus[5],pinNumStatus[6],pinNumStatus[7]);
        
        switch (pin) {
            case 0x0b:
                isPress = true;
                //plugin4Status = !plugin4Status;
                digitalWrite(4, !pinNumStatus[4]);
                break;
            case 0x0d:
                isPress = true;
                //plugin5Status = !plugin5Status;
                digitalWrite(5, !pinNumStatus[5]);
                break;
            case 0x0e:
                isPress = true;
                //plugin6Status = !plugin6Status;
                digitalWrite(6, !pinNumStatus[6]);
                break;
            default:
                isPress = false;
                break;
        }
        
        
        
        vTaskDelay(100 / portTICK_RATE_MS);
    }
    
    i2c_driver_delete(I2C_EXAMPLE_MASTER_NUM);
}


void app_main(void)
{
    
    //start i2c task
    xTaskCreate(i2c_task_example, "i2c_task_example", 2048, NULL, 10, NULL);

}
`

这个是我跟据RTOS 3.x官方例子i2c改的，可以控制到三个按键开关，但加多些判断件条或者写wifi灯，logo灯的GPIO事件就会挂在i2c_example_master_mpu6050_write的i2c_master_cmd_begin上。

**Comment by HoGC** [comment]
你尝试写出来了没

**Comment by HoGC** [comment]
最近我也准备写rtos版的  
交流下 qq：1050517465

**Comment by sonwa** [comment]
还没写出来尼，卡在i2c这里，不同sdk版本有时挂在初始化那里。就是我上面贴的，有时可以运行，有时就一运行就挂在初始化那里了

**Comment by HoGC** [comment]
已经完成RTOS版本 https://github.com/HoGC/esp-aliyun-dc1
使用dc1组件即可
