### ISSUE TITLE
关于OTA

### ISSUE THREAD

**Issue by sonwa** [HoGC/ESP8266_MQTT_DC1#2]
![image](https://user-images.githubusercontent.com/1425134/70301386-30d7be00-1835-11ea-811b-5358a6845cf0.png)

请问你ota的文件怎样生成的？我ota时模块会挂掉的？

BOOT?=new
              APP?=1 //此刻生成的是 user1.bin文件
              SPI_SPEED?=40
              SPI_MODE?=QIO
              SPI_SIZE_MAP?=

BOOT?=new
              APP?=2 //此刻生成的是 user2.bin文件
              SPI_SPEED?=40
              SPI_MODE?=QIO
              SPI_SIZE_MAP?=

我这边这样生成出来ota就挂掉了不成功。

是不是还有什么其它操作？

**Comment by HoGC** [comment]
内存对了吗   为什么你是32Mbit ？user1.4096.new.bin   要是8Mbit的生成user1后一定要clean后再make出user2

**Comment by sonwa** [comment]
我用了另一个模块测ota，内存对的，模块是32Mbit
每次都是 make clean;make COMPILE=gcc 
但是模块是user1时ota就会挂掉，user2是可以更新，但更新完重启都是旧版本来
这个请问一般是些什么原因引起？

**Comment by HoGC** [comment]
尝试使用SPI_SIZE_MAP?=6   下载选择32MBit-C1

**Comment by sonwa** [comment]
还是不行，如果是erase后完整烧录4个文件，第一次是可以ota，然后第二次有新版再要ota就会出现我发那个图的错误。

**Comment by sonwa** [comment]
唉，我知道啥问题了。烧录要用user1.1024.new.2.bin烧，我之前一直用eagle.irom0text.bin来烧。。。
