### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by 02monkey** [HoGC/ESP8266_MQTT_DC1#3]
请问你使用的是什么编译环境?
我用安信可IDE1.5编译报错,用VBOX也错误.

xtensa-lx106-elf-gcc -Os -g -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -ffunction-sections -fdata-sections -fno-builtin-printf -g -Wpointer-arith -Wundef -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals -ffunction-sections -fdata-sections -fno-builtin-printf -fno-guess-branch-probability -freorder-blocks-and-partition -fno-cse-follow-jumps  -DICACHE_FLASH -DSPI_FLASH_SIZE_MAP=6   -I include -I ./ -I ../../include/ets -I ../include -I ../include/mqtt -I ../../include -I ../../include/eagle -I ../../driver_lib/include -I ../../../include -I ../../../include/eagle -I ../../../driver_lib/include  -o .output/eagle/debug/obj/user_main.o -c user_main.c
user_main.c: In function 'mqttConnectedCb':
user_main.c:202:13: error: implicit declaration of function 'dc1_read_gpio' [-Werror=implicit-function-declaration]
  gpio_ret = dc1_read_gpio();
             ^
user_main.c: In function 'mqttDataCb':
user_main.c:407:5: error: implicit declaration of function 'clock_get_timer_task_info_json' [-Werror=implicit-function-declaration]
     clock_get_timer_task_info_json(info_str);
     ^
user_main.c: In function 'user_init':
user_main.c:626:2: error: implicit declaration of function 'set_uart_cb' [-Werror=implicit-function-declaration]
  set_uart_cb(dc1_uart_data_handler);
  ^
cc1.exe: all warnings being treated as errors
make[2]: *** [../../../Makefile:348: .output/eagle/debug/obj/user_main.o] Error 1
make[2]: Leaving directory '/f/esp8266/NonSdk/ESP8266_NONOS_SDK/ESP8266_MQTT_DC1/app/user'
make[1]: *** [../../Makefile:333: .subdirs] Error 2
make[1]: Leaving directory '/f/esp8266/NonSdk/ESP8266_NONOS_SDK/ESP8266_MQTT_DC1/app'
make: *** [../Makefile:333: .subdirs] Error 2

**Comment by HoGC** [comment]
我已经修复了编译错误的问题，你尝试编译看看，
SDK版本使用2.X，工具链使用v4.8.5，安信可IDE需要更改换环境变量。
如果你安装了安信可IDE，其实可以使用win系统终端直接make COMPILE=gcc，配合vscode使用体验更好

**Comment by 02monkey** [comment]
太麻烦了,还是错误,放弃了
